forum-tanya-jawab/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\RegisaterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['guestforum'])->group(function () {
  Route::get('/login', [LoginController::class, 'index'])->name('login.index');
  Route::post('/login', [LoginController::class, 'login'])->name('login.prosses');
  Route::resource('register', RegisaterController::class);
});

Route::middleware(['authforum'])->group(function () {
  Route::get('/', [HomeController::class, 'index'])->name('home');
  Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
  Route::resource('kategori', KategoriController::class);

  Route::get('question', [PertanyaanController::class, 'index'])->name('question.index');
  Route::post('question', [PertanyaanController::class, 'store'])->name('question.store');
});

// CRUD Kategori
Route::resource('kategori', KategoriController::class);


// // Route untuk membuat pertanyaan
// Route::get('/question/create', [QuestionsController::class, 'create']);

// // Route untuk menyimpan inputan kedalam database tabel pertanyaan
// Route::post('/question', [QuestionsController::class, 'store']);

// // Read Data
// // Route mengarah ke halaman tampil semua data di tabel pertanyaan
// Route::get('/question', [QuestionsController::class, 'index']);

// // Route read more
// Route::get('/uestion/{id}', [QuestionsController::class, 'show']);

forum-tanya-jawab/app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';
    protected $fillable = ['name'];
    use HasFactory;
}

forum-tanya-jawab/app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\Pertanyaan;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarkategori = Kategori::all();
        return view('kategori.Kategori', compact('daftarkategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $tambah = new Kategori;

        $tambah->name = $request->nama_kategori;

        $tambah->save();

        return redirect('kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategori = Kategori::where('id', '=', $id)->first();

        $listPertanyaan = Pertanyaan::where('id_kategori', '=', $id)->with(['user', 'kategori'])->get();
        return view('kategori.detail', [
            'kategori' => $kategori,
            'listPertanyaan' => $listPertanyaan
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::all();
        $listPertanyaan = Kategori::find($id);
        return view('questions.edit', ['listPertanyaan' => $listPertanyaan, 'categories' => $kategori]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::find($id);

        $kategori->delete();

        return redirect('/kategori');
    }
}

forum-tanya-jawab/resources/views/kategori/Kategori.blade.php
@extends('layouts.dashboard')

@section('title')
    Halaman Tambah kategori
@endsection

@section('content')
<div class="row mb-3">
  <div class="col-lg-12">
    <button type="button" class="btn btn-sm btn-primary" id="btn-w-modal">
      New category
    </button>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
              <tr>
                  <th>#</th>
                  <th>Category Name</th>
                  <th>Actions</th>
              </tr>
          </thead>
          <tbody>
            @foreach ($daftarkategori as $item)
                <tr>
                  <td>{{$loop->iteration}}</td>
                  <td>{{$item->name}}</td>
                  <td>
                    <form action="/kategori/{{{$item->id}}}" method="POST" class="d-flex flex-lg-row flex-column justify-content-center align-items-center g-4 gap-3">
                        @csrf
                        @method('delete')
                        <a href="/kategori/{{$item->id}}" class="btn btn-info btn-sm mx-3 lg-my-0 my-3">Detail</a>
                        <a href="/kategori/{{$item->id}}/edit" class="btn btn-warning btn-sm mx-3 lg-my-0 my-3">Edit</a>
    
                        <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                    </form>
                </td>
                </tr>
            @endforeach
          </tbody>
      </table>
    </div>
  </div>
</div>

{{-- MODAL --}}
<div class="modal" tabindex="-1" id="modal-tambah-kategori">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{route('kategori.store')}}" method="post">
        @csrf
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
            <input type="text" class="form-control" placeholder="Nama kategori..." name="nama_kategori">
          </div>
        </div>
      </div>
   
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</form>
@endsection

@push('scripts')
    <script>
      $('#dataTable').DataTable({
        
      });

      $('#btn-w-modal').click(function (e) {
        e.preventDefault();

        $('#modal-tambah-kategori').modal('show');
      })
    </script>
@endpush

forum-tanya-jawab/resources/views/kategori/detail.blade.php
@extends('layouts.dashboard')

@section('title')
    {{$kategori->name}}
@endsection

@section('content')
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
              <tr>
                  <th>#</th>
                  <th>Content</th>
                  <th>Created by</th>
                  <th>categories</th>
                  <th>Actions</th>
              </tr>
          </thead>
          <tbody>
            @foreach ($listPertanyaan as $item)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $item->tulisan }}</td>
                  <td>{{ $item->user->name }}</td>
                  <td>{{ $item->kategori->name }}</td>
                  <td>
                    <a href="" class="btn btn-sm btn-success">Detail</a>
                  </td>
                </tr>
            @endforeach
          </tbody>
      </table>
    </div>
  </div>
</div>
@endsection

@push('scripts')
    <script>
      $('#dataTable').DataTable();
    </script>
@endpush